name: dart_attempts
description: Samples, experiments as polymer application
dependencies:
  observe: any
  polymer: any
  dart_attempts_lib:
      path: ../dart-attempts-lib
transformers:
- polymer:
    entry_points:
    - web/external_model/external_model.html
    - web/list/list.html
    - web/indexeddb/indexeddb.html
    - web/screencapture/screencapture.html
    - web/websql/websql.html
